from undo import *

if __name__ == "__main__":
    ed = editor()
    print(ed)
    ed.i('a')
    print(ed)
    ed.u()
    print(ed)
    ed.ctrlr()
    print(ed)
    ed.i('b')
    print(ed)
    ed.i('c')
    print(ed)
    ed.h()
    ed.dw()
    print(ed)
    ed.u()
    print(ed)
    ed.u()
    ed.u()
    print(ed)
    ed.ctrlr()
    print(ed)
    ed.ctrlr()
    ed.ctrlr()
    print(ed)
    ed.iw(" ...")
    print(ed)
    ed.i('z')
    print(ed)
    ed.h(5)
    print(ed)
    ed.x()
    print(ed)
    ed.iw("(Z) ... 1 2 3")
    print(ed)
    ed.iw("Supercalifragilisticexpialidocious")
    print(ed)
    ed.u()
    print(ed)
    ed.ctrlr()
    print(ed)
    ed.u()
    print(ed)
    ed.h()
    ed.i('X')
    print(ed)
    ed.dw()
    print(ed)
